In [2]:
import numpy as np

A=np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [3]:
B=np.array([[5,3],[4,6]])

In [4]:
np.dot(A,B)

array([[13, 15],
       [31, 33]])

In [5]:
A*B

array([[ 5,  6],
       [12, 24]])

In [14]:
C=np.array([[1,0],[1,0]])
C.shape


(2, 2)

In [15]:
B=np.array([7,8])
B

array([7, 8])

In [16]:
np.dot(B,C)

array([15,  0])

In [17]:
x=np.array([[1,2]])
x.shape

(1, 2)

In [18]:
W=np.array([[1,2,3],[4,5,6]])
np.dot(x,W)

array([[ 9, 12, 15]])

In [21]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1=np.array([0.1,0.2,0.3])
print(W1.shape)
print(X.shape)
print(B1.shape)
A1=np.dot(X,W1)+B1
A1

(2, 3)
(2,)
(3,)


array([0.3, 0.7, 1.1])

In [23]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

Z1=sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [24]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])
A2 = np.dot(Z1, W2)+B2
Z2 = sigmoid(A2)


def identity_function(x):
    return x


W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z2, W3)+B3
Z3 = identity_function(A3)


In [25]:
def softmax(x):
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = exp_x/sum_exp_x
    return y


In [26]:

a=np.array([1010,1000,900])
softmax(a)

<ipython-input-25-15d538f4b1bf>:2: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-25-15d538f4b1bf>:4: RuntimeWarning: invalid value encountered in true_divide
  y = exp_x/sum_exp_x


array([nan, nan, nan])

In [30]:
def softmax(x):
    c = np.max(x)
    exp_x = np.exp(x-c)
    sum_exp_x = np.sum(exp_x)
    y = exp_x/sum_exp_x
    return y

np.sum(softmax(a))

1.0

In [28]:
a = np.array([0.3, 2.9, 4.0])
softmax(a)


array([0.01821127, 0.24519181, 0.73659691])

In [31]:
import sys
import os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist

(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True,
                                                  normalize=False)



In [32]:
print(x_train.shape)

(60000, 784)


In [37]:
from PIL import Image

def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

import random
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True,
                                                  normalize=False)
r=int(random.random()*100)
img = x_train[r]
label = t_train[r]
print(label)  # 5
print(img.shape)  # (784,)
img = img.reshape(28, 28)  # 把图像的形状变成原来的尺寸
print(img.shape)  # (28, 28)
img_show(img)


1
(784,)
(28, 28)


In [51]:
import pickle


def get_data():
    (x_train, t_train), (x_test, t_test) =\
        load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test,t_test

def init_network():
    with open('sample_weight.pkl', 'rb') as f:
        network = pickle.load(f)
    return network


def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    a1 = np.dot(x, W1)+b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2)+b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3)+b3
    y = softmax(a3)
    return y

x,t=get_data()
network=init_network()

accuracy_cnt=0
for i in range(len(x)):
    y=predict(network=network,x=x[i])
    p=np.argmax(y)
    if p==t[i]:
        accuracy_cnt+=1
print("Accuracy:"+str(float(accuracy_cnt)/len(x)))




Accuracy:0.9352


In [60]:
x,_=get_data()
network=init_network()
W1,W2,W3=network['W1'],network['W2'],network['W3']
x.shape
W1.shape,W2.shape,W3.shape

((784, 50), (50, 100), (100, 10))

In [64]:
batch_size = 100
accuracy_cnt=0

for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt+=np.sum(p==t[i:i+batch_size])
print("Accuracy:"+str(float(accuracy_cnt)/len(x)))


Accuracy:0.9352


In [67]:
list(range(0,100,100))

[0]