In [34]:
import torch
x= torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [35]:
x.requires_grad_(True)
x.grad


In [36]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

默认为反向传播——其速度比正向传播快，内存占用少

In [37]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

等价于$y=x^Tx$的导数梯度存储在x.grad里面

In [38]:
x.grad == 4*x


tensor([True, True, True, True])

In [39]:
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

Pytorch内，下划线表示会清除原先内容,重写原先内容
默认情况下，PyTorch会累计梯度，所以需要清除原先内容


In [44]:
x.grad.zero_()
print(x)
y=x*x
y.sum().backward()
x.grad

tensor([0., 1., 2., 3.], requires_grad=True)


tensor([0., 2., 4., 6.])

In [45]:
x.grad.zero_()
y = x*x
u = y.detach()#把y当成一个常数而不是关于x的函数
z = u*x
z.sum().backward()
x.grad == u


tensor([True, True, True, True])

In [46]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x


tensor([True, True, True, True])

In [48]:
def f(a):
    b = a*2
    while b.norm() < 1000:
        b = 2*b
    if b.sum() > 0:
        c = b
    else:
        c = 100*b
    return c
a=torch.randn(size=(),requires_grad=True)#size=() mean 一个标量
d=f(a)
d.backward()
a.grad==d/a


tensor(True)