In [1]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2])

In [2]:
x+y,x*y,x/y,x**y


(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [3]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [7]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B=torch.tensor([[1,2,3],[2,4,3],[3,3,9]])

In [10]:
B

tensor([[1, 2, 3],
        [2, 4, 3],
        [3, 3, 9]])

In [12]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [13]:
X=torch.arange(24).reshape(2,3,4)


In [14]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)

In [16]:
B=A.clone()
A,A+B


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [17]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [18]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [19]:
X.sum()


tensor(276)

In [20]:
A.mean(axis=0)


tensor([ 8.,  9., 10., 11.])

In [23]:
print(A)
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [35]:
U=torch.arange(2*20).reshape(2,5,4)

U_sum_axis0=U.sum(axis=[1,2],keepdim=True)
U,U_sum_axis0,U_sum_axis0.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor([[[190]],
 
         [[590]]]),
 torch.Size([2, 1, 1]))

In [29]:
B=torch.ones(4,3)
torch.mm(A,B)


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [31]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [33]:
torch.abs(u).sum()

tensor(7.)

In [34]:
torch.norm(torch.ones(4,9))


tensor(6.)

In [36]:
sum(torch.arange(20))

tensor(190)

NameError: name 'e' is not defined