In [25]:
import torch

x=torch.arange(4.0)

In [26]:
x


tensor([0., 1., 2., 3.])

In [27]:
x.requires_grad_(True)
x.grad
print(x.grad)

None


In [28]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [29]:
y.backward()
print(x.grad)
x.grad

tensor([ 0.,  4.,  8., 12.])


tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad==4*x

tensor([True, True, True, True])

In [30]:
x.grad.zero_()
print(x.grad)
y=x.sum()
y.backward()
x.grad

tensor([0., 0., 0., 0.])


tensor([1., 1., 1., 1.])

In [14]:
x.grad.zero_()
y=x*x
x.sum().backward()
x.grad

tensor([1., 1., 1., 1.])

In [15]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x
z.sum().backward()
x.grad==u



tensor([True, True, True, True])