In [1]:
print(1)

1


In [2]:
import torch

x=torch.tensor(3.0)
y=torch.tensor(2.0)

In [3]:
x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
A=torch.arange(20).reshape(5,4)

In [9]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [12]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [13]:
B==-1*B.T

tensor([[False, False, False],
        [False,  True, False],
        [False, False, False]])

In [14]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
A, A+B


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [16]:
A*B


tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X,(a*X).reshape


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 <function Tensor.reshape>)

In [18]:
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [19]:
A*B
'''Hadamard product:two same size matrix multiply'''

'Hadamard product:two same size matrix multiply'

In [20]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()


(tensor([0., 1., 2., 3.]), tensor(6.))

In [21]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [22]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape
'''由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。等于对列求和'''

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [23]:
A_sum_axis1=A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape
'''对行求和'''

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [24]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [27]:
A.sum(),A.sum(axis=[0,1])

(tensor(190.), tensor(190.))

In [30]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [32]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [33]:
sum_A=A.sum(axis=1,keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [34]:
A/sum_A
'''利用广播机制，即原有的Size矩阵除于每行专属的元素第一行都除于6，第二行都除于22，等等'''

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [36]:
'''点积:内积'''
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [61]:
x=torch.tensor([[1.0,2.0,3.0],[2.0,0,4.0],[3.0,4.0,5.0]])
y=torch.tensor([4.0,3.0,5.0]).reshape(3,1)
y
torch.mm(x,y)

tensor([[25.],
        [28.],
        [49.]])

In [62]:
z=torch.tensor([4.0,3.0,5.0])
torch.mv(x,z)

tensor([25., 28., 49.])

In [78]:
test=torch.mm(x.T,x)
test
torch.norm(test),torch.norm(x)

(tensor(78.6893), tensor(9.1652))

(array([74.359105 +0.j        ,  4.8204475+1.96849242j,
         4.8204475-1.96849242j]),
 array([[-0.43869008+0.j        ,  0.05418693-0.35339392j,
          0.05418693+0.35339392j],
        [-0.47719468+0.j        , -0.81120469+0.j        ,
         -0.81120469-0.j        ],
        [-0.7614698 +0.j        ,  0.4444272 +0.12887172j,
          0.4444272 -0.12887172j]]))

In [79]:
84**(1/2)

9.16515138991168