In [2]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size= 256
train_iter,test_iter=d2l.load_data_fashion_mnist(batch_size)

26422272it [00:03, 7347969.18it/s]                              


Extracting ../data\FashionMNIST\raw\train-images-idx3-ubyte.gz to ../data\FashionMNIST\raw



29696it [00:00, 152643.51it/s]                          


Extracting ../data\FashionMNIST\raw\train-labels-idx1-ubyte.gz to ../data\FashionMNIST\raw



4422656it [00:01, 2566787.63it/s]                             


Extracting ../data\FashionMNIST\raw\t10k-images-idx3-ubyte.gz to ../data\FashionMNIST\raw



6144it [00:00, ?it/s]                   


Extracting ../data\FashionMNIST\raw\t10k-labels-idx1-ubyte.gz to ../data\FashionMNIST\raw



In [3]:
num_inputs=784
num_outputs=10
W=torch.normal(0,0.01,size=(num_inputs,num_outputs),requires_grad=True)
b=torch.zeros(num_outputs,requires_grad=True)

In [6]:
X=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
X.sum(0,keepdim=True),X.sum(1,keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [7]:
def softmax(X):
    X_exp=torch.exp(X)
    patrition=X_exp.sum(1,keepdim=True)
    return X_exp/patrition

keepdim 保持2维矩阵


In [8]:
X = torch.normal(0,1,(2,5))
X_prob=softmax(X)
X_prob,X_prob.sum(1)

(tensor([[0.4815, 0.0249, 0.0798, 0.3044, 0.1093],
         [0.1212, 0.0242, 0.3531, 0.2435, 0.2581]]),
 tensor([1., 1.]))

In [2]:
import torch
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])