In [1]:
import math
import numpy as np
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
max_degree=20
n_train,n_test=100,100
true_w=np.zeros(max_degree)

In [3]:
true_w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [6]:
true_w[0:4]=np.array([5,1.2,-3.4,5.6])
features=np.random.normal(size=(n_train+n_test,1))
print(features)
np.random.shuffle(features)

[[-0.56251712]
 [ 0.11139698]
 [ 0.54606335]
 [ 1.01016555]
 [ 0.37268611]
 [-1.62374626]
 [-0.95371729]
 [-0.38198945]
 [-0.41722795]
 [-1.24742991]
 [-0.61029337]
 [-1.38786813]
 [ 1.67628021]
 [ 0.40637436]
 [-1.18416138]
 [ 1.17364182]
 [ 0.69942254]
 [ 0.44451074]
 [ 2.7837195 ]
 [ 0.66592288]
 [-0.40978064]
 [-0.03054307]
 [-1.57576966]
 [ 1.10034109]
 [-2.53273073]
 [-1.63327056]
 [ 1.26275478]
 [ 2.04538582]
 [ 0.24934707]
 [-0.69687815]
 [-0.63737381]
 [ 0.31996892]
 [ 0.41087772]
 [-0.25952057]
 [ 1.58921629]
 [-0.41631751]
 [-0.70982842]
 [-0.36777923]
 [-0.91769924]
 [-0.39250122]
 [-1.03325476]
 [-0.77469527]
 [-0.4409681 ]
 [-1.06197315]
 [-0.82612544]
 [ 0.49399795]
 [ 1.90773293]
 [-0.78881585]
 [ 0.51335986]
 [ 0.64441987]
 [-0.22076998]
 [ 0.71304959]
 [-0.83020429]
 [ 0.78288101]
 [-0.0114969 ]
 [-0.91530144]
 [-0.09573453]
 [ 0.98624921]
 [ 0.38815345]
 [-0.82673716]
 [ 0.57432986]
 [-1.35515709]
 [-0.1731471 ]
 [ 0.32694272]
 [ 1.29243871]
 [-0.16668947]
 [ 0.32758

In [7]:
features

array([[-0.40126764],
       [-0.0114969 ],
       [-0.83520103],
       [ 0.14970499],
       [ 0.73605095],
       [-0.03054307],
       [-0.83020429],
       [ 0.68147545],
       [ 1.11488743],
       [-0.36516512],
       [ 1.4365105 ],
       [-1.18416138],
       [-0.34561084],
       [-2.31217608],
       [ 0.51335986],
       [ 1.25867531],
       [-1.39911793],
       [-1.77313525],
       [ 1.67628021],
       [-0.72447235],
       [ 0.66592288],
       [-0.03255523],
       [ 0.83645537],
       [ 1.29243871],
       [ 0.70681357],
       [-1.63327056],
       [-0.91769924],
       [ 0.06724939],
       [-2.12062863],
       [-0.74928414],
       [-0.26263656],
       [-0.15681524],
       [-0.77469527],
       [-2.30099946],
       [ 0.37268611],
       [ 0.85386825],
       [-0.88891994],
       [-0.47650812],
       [ 0.86929146],
       [-0.5318963 ],
       [ 1.17364182],
       [ 0.47567237],
       [-0.1990841 ],
       [-0.25952057],
       [ 0.64441987],
       [ 0

In [14]:
poly_features = np.power(features, np.arange(max_degree).reshape(1, -1))
np.arange(max_degree).reshape(1,-1)
poly_features

array([[ 1.00000000e+00, -4.01267644e-01,  1.61015722e-01, ...,
        -1.81292742e-07,  7.27469114e-08, -2.91909818e-08],
       [ 1.00000000e+00, -1.14968962e-02,  1.32178621e-04, ...,
        -1.07119948e-33,  1.23154691e-35, -1.41589670e-37],
       [ 1.00000000e+00, -8.35201026e-01,  6.97560753e-01, ...,
        -4.68217156e-02,  3.91055449e-02, -3.26609912e-02],
       ...,
       [ 1.00000000e+00,  1.30901160e+00,  1.71351136e+00, ...,
         9.72835470e+01,  1.27345291e+02,  1.66696463e+02],
       [ 1.00000000e+00, -1.66257884e+00,  2.76416840e+00, ...,
        -5.66628262e+03,  9.42064158e+03, -1.56625594e+04],
       [ 1.00000000e+00,  4.75145626e-01,  2.25763366e-01, ...,
         3.20667180e-06,  1.52363608e-06,  7.23949020e-07]])

In [10]:
for i in range(max_degree):
    poly_features[:, i] /= math.gamma(i + 1) 

In [13]:
labels=np.dot(poly_features,true_w)
labels,true_w

(array([  4.18444906,   4.9859776 ,   2.26814226,   5.14467774,
          5.33443676,   4.96173583,   2.29798626,   5.32365991,
          5.51820015,   4.28966746,   5.98246363,  -0.35457647,
          4.34367735, -18.40025547,   5.29428732,   5.67829753,
         -2.5629731 ,  -7.67567931,   6.63087194,   2.88347394,
          5.32085552,   4.95909978,   5.3605454 ,   5.72621117,
          5.3284539 ,  -5.56120837,   1.74573224,   5.07329491,
        -14.09059897,   2.75380999,   4.5506652 ,   4.76641782,
          2.61616618, -18.13269388,   5.25941521,   5.36623169,
          1.93441382,   3.94120542,   5.37161716,   3.74032251,
          5.57557158,   5.28661015,   4.68635591,   4.55776506,
          5.31710488,   5.09114223,   5.30525845,   2.60196417,
          6.56924269,   2.32219895,   1.97800095,  -7.9808154 ,
          5.3296852 ,   2.53752566,   4.57941013,   5.24323323,
          5.27639264,   5.26954582,   6.1442123 ,   5.12361378,
          5.50559489,   5.11387079,   5.

In [15]:
labels+=np.random.normal(scale=0.1,size=labels.shape)

In [16]:
true_w, features, poly_features, labels = [torch.tensor(
    x, dtype=torch.float32) for x in [true_w, features, poly_features, labels]]


In [17]:
features[:2],

(tensor([[-0.4013],
         [-0.0115]]),)

In [18]:
def evaluate_loss(net,data_iter,loss):
    metric=d2l.Accumulator(2)
    for X,y in data_iter:
        out=net(X)
        y=y.reshape(out.shape)
        l=loss(out,y)
        metric.add(l.sum(),l.numel())
    return metric[0]/metric[1]

In [ ]:
def train(train_features, test_features, train_labels, test_labels,
          num_epochs=400):
    loss = nn.MSELoss(reduction="none")
    input_shape = train_features.shape[-1]
    net = nn.Sequential(nn.Linear(input_shape, bias=False))
    batch_size = min(10, train_labels.shape[0])
    train_iter = d2l.load_array((train_features, test_labels.reshape(-1, -1)),
                                batch_size)
    test_iter = d2l.load_array((test_features, test_labels.reshape(-1, 1)),
                               batch_size, is_train=False)
    trainer = torch.optim.SGD(net.parameters(), lr=0.01)
    animator = d2l.Animator(xlabel='epoch', ylabel='loss', yscale='log',
                            xlim=[1, num_epochs], ylim=[1e-3, 1e2],
                            legend=['train', 'test'])
    