In [1]:
import torch
from torch import nn
from torch.nn import functional as F

net=nn.Sequential(nn.Linear(20,256),nn.ReLU(),nn.Linear(256,10))
X=torch.rand(2,20)
print("X=",X)
net(X)

X= tensor([[0.0509, 0.9727, 0.2538, 0.1576, 0.2291, 0.0035, 0.7830, 0.1919, 0.7545,
         0.7568, 0.0299, 0.1084, 0.3808, 0.3783, 0.8466, 0.7555, 0.1019, 0.7406,
         0.3554, 0.6740],
        [0.3647, 0.2646, 0.7967, 0.6978, 0.1987, 0.1012, 0.6718, 0.5147, 0.0136,
         0.9646, 0.0215, 0.0847, 0.4042, 0.1050, 0.2495, 0.6233, 0.3992, 0.5001,
         0.6909, 0.1654]])


tensor([[-0.1915, -0.1658, -0.0278, -0.0079, -0.0361, -0.0168, -0.0294,  0.3559,
          0.1690,  0.0442],
        [-0.1326, -0.0998,  0.0186, -0.1233, -0.0156, -0.1111, -0.0094,  0.2877,
          0.2395,  0.0219]], grad_fn=<AddmmBackward0>)

In [2]:
class MLP(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.hideen = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)

    def forward(self, X):
        return self.out(F.relu(self.hideen(X)))


In [3]:
net=MLP()
print(X)
net(X)

tensor([[0.0509, 0.9727, 0.2538, 0.1576, 0.2291, 0.0035, 0.7830, 0.1919, 0.7545,
         0.7568, 0.0299, 0.1084, 0.3808, 0.3783, 0.8466, 0.7555, 0.1019, 0.7406,
         0.3554, 0.6740],
        [0.3647, 0.2646, 0.7967, 0.6978, 0.1987, 0.1012, 0.6718, 0.5147, 0.0136,
         0.9646, 0.0215, 0.0847, 0.4042, 0.1050, 0.2495, 0.6233, 0.3992, 0.5001,
         0.6909, 0.1654]])


tensor([[-0.1469, -0.0201, -0.0320,  0.2774,  0.0065, -0.1908, -0.2092,  0.0758,
          0.0300,  0.0707],
        [-0.2146, -0.0253,  0.0570,  0.2123,  0.0678, -0.1403, -0.1304, -0.0529,
          0.0195,  0.0429]], grad_fn=<AddmmBackward0>)

In [4]:
class MySequential(nn.Module):
    def __init__(self,*args) -> None:
        super().__init__()
        for idx,module in enumerate(args):
            self._modules[str(idx)]=module
    
    def forward(self,X):
        for block in self._modules.values():
            X=block(X)
        return X
    
net=MySequential(nn.Linear(20,256),nn.ReLU(),nn.Linear(256,10))
net(X)

tensor([[ 0.0050, -0.0919, -0.2138, -0.0950, -0.2421, -0.1544, -0.0868,  0.0694,
          0.0235,  0.1739],
        [ 0.0092, -0.1197,  0.0305, -0.0495, -0.1591, -0.1111, -0.1146,  0.0492,
         -0.0576,  0.0058]], grad_fn=<AddmmBackward0>)

In [5]:
nn.Linear(20,20,bias=False)

Linear(in_features=20, out_features=20, bias=False)

In [6]:
import torch 
from torch import nn
# def try_gpu(i=0):
#     if torch.cuda.device_count()>=i+1:
#         return torch.device(f'cuda:{i}')
#     return torch.device('cpu')
net=nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
X=torch.rand(size=(2,4))
net(X)

tensor([[-0.3986],
        [-0.3627]], grad_fn=<AddmmBackward0>)

In [7]:
print(net[2].state_dict())

OrderedDict([('weight', tensor([[ 0.3246,  0.1468, -0.3037,  0.1295, -0.2617,  0.2707, -0.0832,  0.1318]])), ('bias', tensor([-0.3237]))])


In [8]:
net[0].state_dict(),X

(OrderedDict([('weight',
               tensor([[-0.1594,  0.2541,  0.1882, -0.2645],
                       [ 0.3021, -0.0837, -0.4823, -0.3813],
                       [-0.1459,  0.2681, -0.2281, -0.0260],
                       [-0.3542,  0.1668,  0.0715,  0.0093],
                       [-0.1310, -0.3949,  0.4333, -0.3455],
                       [-0.4803, -0.4009,  0.1375, -0.4029],
                       [-0.2500, -0.3025,  0.2902,  0.1673],
                       [ 0.1114,  0.1963, -0.2280,  0.0806]])),
              ('bias',
               tensor([-0.4489,  0.0115,  0.4341,  0.2400, -0.0642,  0.1589, -0.1762, -0.1913]))]),
 tensor([[0.0120, 0.2670, 0.4548, 0.9402],
         [0.8710, 0.2419, 0.9341, 0.4683]]))

In [9]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([-0.3237], requires_grad=True)
tensor([-0.3237])


In [10]:
net[2].weight.grad==None

True

In [11]:
print(*[(name,param.shape) for name,param in net[0].named_parameters()])
print(*[(name,param.shape) for name,param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [12]:
net.state_dict()['2.bias'].data

tensor([-0.3237])

In [13]:
def block1():
    return nn.Sequential(nn.Linear(4,8),nn.ReLU(),
                         nn.Linear(8,4),nn.ReLU())
def block2():
    net=nn.Sequential()
    for i in range(4):
        net.add_module(f'block{i}',block1())
    return  net
rgnet=nn.Sequential(block2(),nn.Linear(4,1))
rgnet(X)

tensor([[-0.0885],
        [-0.0885]], grad_fn=<AddmmBackward0>)

In [14]:
print(rgnet)

Sequential(
  (0): Sequential(
    (block0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [15]:
rgnet[0][1][0].bias.data

tensor([-0.2500,  0.0530,  0.4566, -0.2292,  0.4641,  0.1224, -0.4850,  0.2535])

In [16]:
def init_normal(m):
    if type(m)==nn.Linear:
        nn.init.normal_(m.weight,mean=0,std=0.01)
        nn.init.zeros_(m.bias)
net.apply(init_normal)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [17]:
net[0].weight.data[0],net[0].bias.data[0]

(tensor([-0.0020,  0.0006,  0.0051, -0.0054]), tensor(0.))

In [18]:
x=torch.arange(4)
torch.save(x,'f-file')

In [19]:
x2=torch.load('f-file')

In [20]:
x2,x

(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

In [21]:
x2==x

tensor([True, True, True, True])

In [22]:
y=torch.zeros(4)
torch.save([x,y],'f-file')

In [23]:
x2,y2=torch.load('f-file')

In [24]:
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [25]:
z=torch.zeros((4,4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
torch.save([x,y,z],'f-file')

In [27]:
x1,y1,z1=torch.load('f-file')

In [28]:
z1==z

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [29]:
mydict={'x':x1,'y':y1,'z':z1}
torch.save(mydict,'mydict')
mydict1=torch.load('mydict')
mydict1

{'x': tensor([0, 1, 2, 3]),
 'y': tensor([0., 0., 0., 0.]),
 'z': tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]])}

In [30]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net=MLP()
X=torch.randn(size=(2,20))
Y=net(X)

In [31]:
torch.save(net.state_dict(),'mlp.params')

In [32]:
clone=MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()#用来让模型“准备好”，以便下面的语句接收测试数据。

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [33]:
Y_clone=clone(X)
Y_clone==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])