In [1]:
import numpy as np

from PIL import Image

def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

def mean_squared_error(y, t):
    return 0.5*np.sum((y-t)**2)


t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]

mean_squared_error(np.array(y),np.array(t))

0.09750000000000003

从人工设计规则转变为由机器从数据中学习：没有人为介入的方块用灰色表示
深 度 学 习 有 时 也 称 为 端 到 端 机 器 学 习（end-to-end machine
learning）。这里所说的端到端是指从一端到另一端的意思，也就是
从原始数据（输入）中获得目标结果（输出）的意思。

In [2]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t*np.log(y+delta))

cross_entropy_error(np.array(y),np.array(t))

0.510825457099338

### 交叉熵误差
$$E=-\sum\limits_k t_k log y_k $$
$y_k$对应是神经网络的输出，$t_k$是正确解标签。由于$t_k$中只有正确解标签的索引为1，其他均为0，(one-hot表示).

In [3]:
import sys,os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist

In [4]:
(x_train,t_train),(x_test,t_test)=load_mnist(normalize=True,one_hot_label=True)



In [5]:
train_size=x_train.shape[0]
print(train_size)
batch_size=10
batch_mask=np.random.choice(train_size,batch_size)
batch_mask

60000


array([12203, 36689, 43616, 55616, 46505, 44671, 36697, 27307, 32025,
       58166])

In [6]:
x_batch=x_train[100].reshape(28,28)
img_show(x_batch*255)
t_batch=t_train[100]
t_batch

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [8]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        #这里的if语句是输入一个图像的时候需要改变数据的形状。
    batch_size = y.shape[0]
    print(f'batch_size={batch_size}')
    return -np.sum(t*np.log(y+1e-7))/batch_size


array([0.69314718, 1.60943791])

0.6931471805599453

In [11]:

import numpy as np
import sys
import os
sys.path.append(os.pardir)
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self) -> None:
        self.W = np.random.randn(2, 3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        return loss


In [16]:
net=simpleNet()
print(net.W)

[[ 0.02471963  1.6837844   0.07445007]
 [ 2.13886089 -0.8392318  -1.06155502]]


In [17]:
x=np.array([0.6,0.9])
p=net.predict(x)
print(p)

[ 1.93980658  0.25496202 -0.91072948]


In [18]:
np.argmax(p)

0

In [30]:
t=np.array([0,0,0])
net.loss(x,t)

0.21775821755027033

In [31]:
def f(W):
    return net.loss(x,t)

dW=numerical_gradient(f,net.W)
print(dW)

[[-0.11740811  0.08950788  0.02790024]
 [-0.17611217  0.13426182  0.04185035]]
