In [23]:
import  numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w=torch.tensor([2,-3.4])
true_b=4.2
features,labels=d2l.synthetic_data(true_w,true_b,1000)



In [24]:
def load_array(data_arrays,batch_size,is_train=True):
    dataset=data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [25]:
batch_size=10
data_iter=load_array((features,labels),batch_size)

In [26]:
next(iter(data_iter))

[tensor([[-0.6269,  0.8479],
         [ 0.4050, -0.1185],
         [ 0.9039, -0.8469],
         [ 1.0950, -2.3143],
         [ 0.0787, -0.2749],
         [-1.5898,  0.4810],
         [ 0.3279,  0.2151],
         [ 0.0481, -1.2079],
         [ 0.9295,  0.4077],
         [-0.2307,  0.9486]]),
 tensor([[ 0.0518],
         [ 5.4162],
         [ 8.8929],
         [14.2590],
         [ 5.3089],
         [-0.6246],
         [ 4.1305],
         [ 8.3957],
         [ 4.6801],
         [ 0.4911]])]

In [27]:
from torch import nn
net=nn.Sequential(nn.Linear(2,1))



In [28]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [29]:
print(net[0].weight.data.normal_(0,0.01))

tensor([[-0.0135, -0.0005]])


In [30]:
loss=nn.MSELoss()
trainer=torch.optim.SGD(net.parameters(),lr=0.03)


In [31]:
num_epoch=3
for epoch in range(num_epoch):
    for X,y in data_iter:
        l=loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l=loss(net(features),labels)
    print(f'epoch {epoch+1}, loss {l:f}')

epoch 1, loss 0.000166
epoch 2, loss 0.000100
epoch 3, loss 0.000101


In [32]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)


w的估计误差： tensor([-0.0003, -0.0005])
b的估计误差： tensor([-0.0010])
