In [2]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self) -> None:
        super().__init__()

    def forward(self, X):
        return X-X.mean()


In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))


tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [6]:
Y=net(torch.rand(4,8))

In [7]:
Y.mean()

tensor(-3.0268e-09, grad_fn=<MeanBackward0>)

In [8]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units) -> None:
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))
    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)


In [9]:
linear=MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[-1.7523,  0.2839, -0.1120],
        [-1.1500,  0.0103,  0.9852],
        [-0.9990, -0.2840,  2.6255],
        [ 0.8518, -1.3375, -1.8936],
        [ 0.9872, -0.3283, -0.6296]], requires_grad=True)

In [10]:
linear(torch.rand(2,5))

tensor([[0.2833, 0.0000, 1.1821],
        [0.0000, 0.0000, 1.8696]])